### ISSUE TITLE
Przygotowanie projektu wizualnego strony

### ISSUE THREAD

**Issue by pktiuk** [sjopinie/sjopinie#2]
Przygotowanie projektu wizualnego strony 

W tym takich stron jak:

- [x] strona główna
- [x] strona dodawania przedmiotu
- [x] wyszukiwarka (szukamy po nazwie, prowadzącym, tagach i po liczbie gwiazdek 0-10)
   - wraz z wyświetlonymi wynikami
- [x] Strona danego lektoratu
    - wraz z komentarzami, tagami, wadami, zaletami etc.

(Całkowicie opcjonalnie) Można by też przygotować jakieś logo dla strony, ale to nic pilnego i może poczekać

**Comment by pktiuk** [comment]
Przykładowe strony:
https://weiti.pw/main.php  
https://www.ratemyprofessors.com/

Wymagania funkcjonalne (aby łatwiej było ocenić co powinno się znaleźć):  
https://docs.google.com/document/d/18WaJ4cBeMyGQWM9v00GtT7COrY_qx39MQTAwQaQSazE/edit?usp=sharing

**Comment by pktiuk** [comment]
Co do wyglądu strony prowadzącego/przedmiotu dobrą inspiracją może być ceneo
![obraz](https://user-images.githubusercontent.com/45544416/126874149-3f6a1d0a-977e-4008-8248-1cdcb3002b12.png)

**Comment by ghost** [comment]
Aktualnie zrobiłem taki projekt. Kolory wybrane losowo. Wymaga jeszcze poprawek, jak zmiana czcionki, inne ułożenie niektórych elementów oraz dodanie kilku funkcji. Zajmę się tym później. Czy taki styl będzie dobry?

![przyklad](https://user-images.githubusercontent.com/87905820/127382539-94b7cb6c-2532-477e-a9a3-3198e79ffc49.jpg)

**Comment by pktiuk** [comment]
Wygląda bardzo spoko, jest to coś, z czym można zacząć pracować.

Jako podsumowanie mam kilka uwag
- co do kolorów to się nimi wcale nie przejmuj, można to potem bardzo łatwo zmienić w jednym miejscu
- trochę brakuje mi tu elementów nawigacyjnych (tzn. elementów wspólnych dla wszystkich podstron), przydałby się może jeszcze poza tym jakiś przycisk do logowania/wylogowywania.

**Comment by ghost** [comment]
**Poprawka strony lektoratu. Dodane kilka funkcji, zmiana położenia przycisku dodaj opinię i ogólna poprawka elementów (ich wielkości itp.)**
![lektorat-v1 1](https://user-images.githubusercontent.com/87905820/127780667-7de15453-b606-465e-b17c-f3c920e7a482.jpg)

**Przykład strony głównej. Wygląd i działanie na wzór wielu wyszukiwarek, ale myślę, że jednak coś innego zrobię.**
![stronaglowna1-v1 0](https://user-images.githubusercontent.com/87905820/127780706-6da24b9d-5ba9-459c-8957-15a9be4c0afc.jpg)
![stronaglowna2-v1 0](https://user-images.githubusercontent.com/87905820/127780707-b612ac26-18f6-4109-8784-42926ffb3781.jpg)

**Przykład strony z wynikami wyszukiwania.**
![wynikwyszukiwania-v1 0](https://user-images.githubusercontent.com/87905820/127780744-93b3d033-22f9-43b5-b38f-e674d6d97944.jpg)

__
Napiszcie co myślicie o tym. Jutro dokończę i wyślę stronę dodawania przedmiotu. Pozdro!

**Comment by pktiuk** [comment]
Wygląda dobrze, tylko nie wiem, czy potrzebujemy funkcji wyszukiwania opinii w widoku przedmiotu.  
@ProtegerPW @tiskus333  Co sądzicie?

![obraz](https://user-images.githubusercontent.com/45544416/127780994-7aab026c-c369-45f7-ae13-ca27df284fa6.png)

Poza tym powiedz mi, jak rozumiesz działanie tego paska wyszukiwania?  
Czy ma on wyszukiwać po jednej z wybranych rzeczy (tzn. szukamy albo po tagach, albo po nazwie zajęć, albo po prowadzącym), czy też umożliwiać jakieś kombinacje tych elementów?

**Comment by ghost** [comment]
Działanie na zasadzie wyszukiwania po słowach kluczowych. Przykład, jest strona lektoratu na której jest 130 opinii i ktoś chce znaleźć wpis, który widział już wcześniej i pamięta kilka słów. Trochę pomocne ale może rzeczywiście nie potrzebne.

**Comment by pktiuk** [comment]
W sumie pomysł spoko, ale jego implementacje lepiej zostawić na później.  
Jak chcesz to możesz go dopisać do wymagań funkcjonalnych z jakimś niskim priorytetem. (na początku nie będziemy mieć raczej problemu ze zbyt dużą liczbą opinii ;) )

A jak z tym wyszukiwaniem zwykłym? (Tym z głównej strony i ze strony z wyszukiwaniami)
>Czy ma on wyszukiwać po jednej z wybranych rzeczy (tzn. szukamy albo po tagach, albo po nazwie zajęć, albo po prowadzącym), czy też umożliwiać jakieś kombinacje tych elementów?

**Comment by tiskus333** [comment]
Jak dla mnie wygląda super. Co do wyszukiwania wśród opinii mogłoby być przydatne, ale rzeczywiście nie jest to coś czym powinniśmy się na razie przejmować. Funkcjonalności nie ma na początku co mnożyć na siłę.

>A jak z tym wyszukiwaniem zwykłym? (Tym z głównej strony i ze strony z wyszukiwaniami)
>Czy ma on wyszukiwać po jednej z wybranych rzeczy (tzn. szukamy albo po tagach, albo po nazwie zajęć, albo po prowadzącym), czy też umożliwiać jakieś kombinacje tych elementów?

Można by było spróbować zrobić tak jak jest w sklepach internetowych, że jak wpiszesz frazę to leci search po wszystkim, a z boku masz kategorie do których pasuje i można sobie zawęzić np.: Prowadzący Przedmiot Opinia itd.. Wyjdzie podobnie jak wybranie na początku czego chcemy szukać, ale w moim przekonaniu mniej narzucające/ograniczające użytkownika.

coś w tym stylu:
![image](https://user-images.githubusercontent.com/48092529/127887501-4d7f1362-8242-4efa-898c-9870b15bd3b8.png)

**Comment by ProtegerPW** [comment]
tak jak wcześniej mówili - pod względem projektu - super

**Comment by pktiuk** [comment]
No to mamy dogadane, teraz można przejść do prób zakodzenia tego.

**Comment by ghost** [comment]
Zrobiłem parę nowych projektów i zmieniłem trochę wygląd całej strony. Niedługo biorę się za pisanie strony i już tam będę się bawić wyglądem. 

__

![01 Strona główna - sjopinie pl](https://user-images.githubusercontent.com/87905820/136445955-ab5c7c0f-16a3-4c13-8ab1-9233288c9d73.png)
Projekt strony głównej dla użytkowników nie zalogowanych. W opisie strony po prawej przekierowanie do rejestracji. Ewentualnie doda się później jeszcze przycisk 'Zarejestruj się' w prawym górnym rogu.

![02 Ekran początkowy - sjopinie pl](https://user-images.githubusercontent.com/87905820/136445959-dc7b31ff-54fd-4acb-8c56-e23e662c33e7.png)
Przykładowa strona co mógłby widzieć użytkownik zaraz po zalogowaniu. Myślę, że tutaj powinna znaleźć tablica z wszystkimi przedmiotami, aby je przeglądać, np. alfabetycznie bez wyszukiwania.

![03 Wyszukiwanie - sjopinie pl – 1](https://user-images.githubusercontent.com/87905820/136445960-aa197884-cd40-4b7c-b4d4-73ef9292b9b8.png)
Wyszukiwarka

![04 Wynik wyszukiwania - sjopinie pl](https://user-images.githubusercontent.com/87905820/136445965-bd80500e-41c3-43fb-a84f-78b0eefc842a.png)
Wynik wyszukiwania

![05 Nazwa przedmiotu- opinia - sjopinie pl](https://user-images.githubusercontent.com/87905820/136445967-489ac78f-a5e5-4f42-9648-c3ee2cb7e871.png)
Przykładowa strona przedmiotu

![06 Dodaj opinię - sjopinie pl](https://user-images.githubusercontent.com/87905820/136445970-3ee5c4cb-de87-4929-9fd2-da771a6895b9.png)
Dodawanie opinii

![07 Dodaj przedmiot - sjopinie pl – 1](https://user-images.githubusercontent.com/87905820/136445973-fe4a90d0-ef8e-4720-838a-6d296d3bd9a6.png)
Dodawanie przedmiotu
